export const PRODUCT_POSTING = "PRODUCT_ISPOSTING";
export const PRODUCT_POST_SUCESS = "PRODUCT_POST_SUCESS";

export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_LOADING_SUCESS = "PRODUCT_LOADING_SUCESS";
